server:
  port: 6370

spring:
  redis:
    host: 192.168.1.152
    password: 123456
    port: 6379
    database: 0
    lettuce:
      pool:
        max-wait: -1
        max-active: 200
        max-idle: 10
        min-idle: 0


